// List of packs + their REGULAR price.
// Kept separate from the calculation logic (script.js) so you can add new
// packs here without touching anything else.
//
// IMPORTANT: type the price exactly as the game shows it ("400OC", "1,5N",
// "6K", ...) -- no math needed, toNumber() in script.js parses it for you.
//
// Add a new pack by copying a line and changing name + price, e.g.:
//   { name: "Wind", price: "225OC" },

const PACKS = [
  { name: "Pirate", price: "100" },
  { name: "Ninja", price: "650" },
  { name: "Soul", price: "6K" },
  { name: "Slayer", price: "250K" },
  { name: "Sorcerer", price: "50M" },
  { name: "Dragon", price: "5B" },
  { name: "Fire", price: "50B" },
  { name: "Hero", price: "250B" },
  { name: "Hunter", price: "1T" },
  { name: "Solo", price: "3,5T" },
  { name: "Titan", price: "12,5T" },
  { name: "Chainsaw", price: "45T" },
  { name: "Flight", price: "250T" },
  { name: "Ego", price: "3Q" },
  { name: "Clover", price: "12,5Q" },
  { name: "Ghoul", price: "50Q" },
  { name: "Geass", price: "100Q" },
  { name: "Bizarre", price: "150Q" },
  { name: "Fairy", price: "250Q" },
  { name: "Sins", price: "450Q" },
  { name: "Note", price: "2QN" },
  { name: "Slime", price: "5QN" },
  { name: "Mage", price: "15QN" },
  { name: "Zero", price: "50QN" },
  { name: "Vagrant", price: "125QN" },
  { name: "Rebellion", price: "350QN" },
  { name: "Viking", price: "700QN" },
  { name: "Mercenary", price: "1,25S" },
  { name: "Online", price: "3,25S" },
  { name: "Fate", price: "10S" },
  { name: "Shadow", price: "15S" },
  { name: "Lord", price: "22,5S" },
  { name: "Spy", price: "40S" },
  { name: "Assassin", price: "75S" },
  { name: "Alchemist", price: "135S" },
  { name: "Reincarnation", price: "265S" },
  { name: "Elite", price: "500S" },
  { name: "Basketball", price: "1SP" },
  { name: "Stone", price: "2SP" },
  { name: "Showdown", price: "4SP" },
  { name: "Classroom", price: "6SP" },
  { name: "Revenger", price: "10SP" },
  { name: "Paranormal", price: "20SP" },
  { name: "Psychic", price: "35SP" },
  { name: "Cleaner", price: "65SP" },
  { name: "Stray", price: "100SP" },
  { name: "Paradise", price: "175SP" },
  { name: "Monster", price: "250SP" },
  { name: "Adventure", price: "500SP" },
  { name: "Muscle", price: "750SP" },
  { name: "Spirit", price: "1OC" },
  { name: "Feudal", price: "1,5OC" },
  { name: "Exorcist", price: "2OC" },
  { name: "Meister", price: "2.5OC" },
  { name: "Love", price: "3OC" },
  { name: "Cosplay", price: "4OC" },
  { name: "Boxing", price: "5OC" },
  { name: "Fighting", price: "6OC" },
  { name: "Disastrous", price: "7.5OC" },
  { name: "Silver", price: "10OC" },
  { name: "Apothecary", price: "15OC" },
  { name: "Butler", price: "22.5OC" },
  { name: "Superpower", price: "30OC" },
  { name: "Idol", price: "42.5OC" },
  { name: "Warlord", price: "52.5OC" },
  { name: "Cloud", price: "65OC" },
  { name: "Espada", price: "80OC" },
  { name: "Moon", price: "100OC" },
  { name: "Curses", price: "125OC" },
  { name: "Destruction", price: "150OC" },
  { name: "Sailor", price: "175OC" },
  { name: "Saint", price: "200OC" },
  { name: "Wind", price: "225OC" },
  { name: "Tournament", price: "250OC" },
  { name: "Shield", price: "275OC" },
  { name: "Horizon", price: "300OC" },
  { name: "Heartbound", price: "325OC" },
  { name: "Quintuplets", price: "350OC" },
  { name: "Goblin", price: "375OC" },
  { name: "Dungeon", price: "400OC" },
];
